# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nomes.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Janela(object):
    def setupUi(self, Janela):
        Janela.setObjectName("Janela")
        Janela.resize(242, 133)
        self.centralwidget = QtWidgets.QWidget(Janela)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_nome = QtWidgets.QLabel(self.centralwidget)
        self.label_nome.setObjectName("label_nome")
        self.gridLayout.addWidget(self.label_nome, 0, 0, 1, 1)
        self.lineEdit_nome = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_nome.setObjectName("lineEdit_nome")
        self.gridLayout.addWidget(self.lineEdit_nome, 0, 1, 1, 1)
        self.label_sobrenome = QtWidgets.QLabel(self.centralwidget)
        self.label_sobrenome.setObjectName("label_sobrenome")
        self.gridLayout.addWidget(self.label_sobrenome, 1, 0, 1, 1)
        self.lineEdit_sobrenome = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_sobrenome.setObjectName("lineEdit_sobrenome")
        self.gridLayout.addWidget(self.lineEdit_sobrenome, 1, 1, 1, 1)
        self.pushButton_unir = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_unir.setObjectName("pushButton_unir")
        
        self.pushButton_unir.clicked.connect(self.unir)
        
        self.gridLayout.addWidget(self.pushButton_unir, 2, 1, 1, 1)
        self.label_completo = QtWidgets.QLabel(self.centralwidget)
        self.label_completo.setObjectName("label_completo")
        self.gridLayout.addWidget(self.label_completo, 3, 0, 1, 1)
        self.lineEdit_completo = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_completo.setObjectName("lineEdit_completo")
        self.gridLayout.addWidget(self.lineEdit_completo, 3, 1, 1, 1)
        Janela.setCentralWidget(self.centralwidget)

        self.retranslateUi(Janela)
        QtCore.QMetaObject.connectSlotsByName(Janela)

    def retranslateUi(self, Janela):
        _translate = QtCore.QCoreApplication.translate
        Janela.setWindowTitle(_translate("Janela", "Junta Nomes"))
        self.label_nome.setText(_translate("Janela", "Nome:"))
        self.label_sobrenome.setText(_translate("Janela", "Sobrenome:"))
        self.pushButton_unir.setText(_translate("Janela", "UNIR"))
        self.label_completo.setText(_translate("Janela", "Nome Completo:"))
        
        
    def unir(self):
        nome = self.lineEdit_nome.text()
        sobrenome = self.lineEdit_sobrenome.text()
        completo = nome + " " + sobrenome
        self.lineEdit_completo.setText(completo)
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Janela = QtWidgets.QMainWindow()
    ui = Ui_Janela()
    ui.setupUi(Janela)
    Janela.show()
    sys.exit(app.exec_())
